### ISSUE TITLE
Support for "extra-path" component from RFC3875

### ISSUE THREAD

**Issue by arxcode** [michael-lazar/jetforce#16]
RFC 3875 supports an "extra-path" component for CGI scripts; i.e. one can call a CGI script with a URL like gemini://mozz.us/cgi-bin/debug.cgi/this/is/extra?foobar and the server would identify debug.cgi as the CGI script to execute, passing the "/this/is/extra" path along as PATH_INFO variable.

Is this something that could be considered for jetforce? Or is this something that would be alien to the Gemini protocol? It would enable the use of a single CGI script that would manage e.g. comments for all blog entries in a personal blog, by passing the blog post in question as extra path.

**Comment by michael-lazar** [comment]
Hi! I'm open to adding this feature, assuming the implementation can be made reasonably clean and straightforward. I don't see any reason that this would conflict with gemini from a protocol level.

Current the PATH_INFO in jetforce will return the whole path in the URL, including the CGI script. In your example it would be

```
PATH_INFO=/cgi-bin/debug.cgi/this/is/extra
```

Are you saying that this is incorrect with regards to RFC 3875, and it should only be sending

```
PATH_INFO=/this/is/extra
```

In this case, if the URL was ``gemini://mozz.us/cgi-bin/debug.cgi?foobar``, should ``PATH_INFO`` be empty?

**Comment by arxcode** [comment]
At the moment, the most straightforward implementation I can think of is to iterate through the path components from left to right until one hits a path that is no longer a directory.

Regarding PATH_INFO in RFC3875: Yes, that is my understanding from section [4.1.5](https://tools.ietf.org/html/rfc3875#section-4.1.5) and the example in section [4.1.6](https://tools.ietf.org/html/rfc3875#section-4.1.6):

> It identifies the resource or sub-resource to be returned by the CGI script, and is derived from the portion of the URI path hierarchy **following the part that identifies the script itself**.

Given that the README says that jetforce "doesn't exactly follow the RFC 3875 specification", this is not a big problem, IMHO, however.

**Comment by michael-lazar** [comment]
Closing as this has now been merged into master and will be included in the next release. Thanks again for the PR!
