### ISSUE TITLE
add a option to see the 'jetforce' version

### ISSUE THREAD

**Issue by cremesk** [michael-lazar/jetforce#2]
I have just looked at jetforce and find it very well done! One thing I noticed is that can we please add an option to display the jetforce version? Like: ‘jetforce -v’

Thanks
~creme

**Comment by tallship** [comment]
JetForce displays the version when it is running. So it always displays on startup (although it does eventually scroll off the screen after the logs push it up following several connections).

The version is also listed in setup.py. It's not a bad idea, but do you still think that ./jetforce.py -v should be implemented?

**Comment by cremesk** [comment]
Thank you for your answer.
i have installed 'jetforce' with pip. I think that it is very tedious every time to crawl through paths in order to read a version of the program. For me, jetforce also runs as a service on a server so it's also a bit awkward to look at the launch of the Jetforce on which version it is.

the easiest way is in my opinion for a user if you can read the version directly from the program.
so it is possible to easily check if you are using the latest version.

What do you think?

**Comment by tallship** [comment]
I think it could be a good idea as it's a standard method for checking versioning on daemons and other software installations - just wasn't sure if how aware you were of where the versioning was displayed right now :)

If you're installing it as a service, then it might be even more relevant, like php -v or apache, nginx or even python. Jetforce already has a usage Right now ./jetforce.py does display the version but it also tries to start and bind to an address if issued without any arguments.

**Comment by michael-lazar** [comment]
Hello!

I think this is a perfectly reasonable request. I went ahead and added this feature in https://github.com/michael-lazar/jetforce/commit/378d58a50292e99859194f0bdf69ee8245268976

I prefer to use capital ``V`` for displaying the version, because lowercase ``v`` is often used by applications for setting the logging verbosity.

```
$ jetforce -V
jetforce 0.1.0

$ jetforce --version
jetforce 0.1.0
```

FYI, you can also use pip to check the version that you currently have installed

```
$ pip show jetforce
Name: Jetforce
Version: 0.1.0
Summary: An Experimental Gemini Server
Home-page: https://github.com/michael-lazar/jetforce
Author: Michael Lazar
Author-email: lazar.michael22@gmail.com
License: Other/Proprietary License
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by:
```
