### ISSUE TITLE
Connecting through Bombadillo throws errors in console. 

### ISSUE THREAD

**Issue by kayew** [michael-lazar/jetforce#21]
Through Bombadillo, I cannot connect to my own site. Using other clients like, asuka and AV-98, I can easily connect. When I try to connect using Bombadillo, jetforce throws this into the logs:
```
May 18 15:49:04 hermes jetforce[31639]: Task exception was never retrieved
May 18 15:49:04 hermes jetforce[31639]: future: <Task finished coro=<GeminiServer.accept_connection() done, defined at /usr/local/bin/jetforce:664> exception=ConnectionResetError('Connection lost')>
May 18 15:49:04 hermes jetforce[31639]: Traceback (most recent call last):
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 490, in handle
May 18 15:49:04 hermes jetforce[31639]:     await self.parse_header()
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 547, in parse_header
May 18 15:49:04 hermes jetforce[31639]:     data = await self.reader.readuntil(b"\r\n")
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/lib/python3.7/asyncio/streams.py", line 585, in readuntil
May 18 15:49:04 hermes jetforce[31639]:     raise IncompleteReadError(chunk, None)
May 18 15:49:04 hermes jetforce[31639]: asyncio.streams.IncompleteReadError: 0 bytes read on a total of None expected bytes
May 18 15:49:04 hermes jetforce[31639]: During handling of the above exception, another exception occurred:
May 18 15:49:04 hermes jetforce[31639]: Traceback (most recent call last):
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 672, in accept_connection
May 18 15:49:04 hermes jetforce[31639]:     await request_handler.handle(reader, writer)
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 494, in handle
May 18 15:49:04 hermes jetforce[31639]:     return await self.close_connection()
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 597, in close_connection
May 18 15:49:04 hermes jetforce[31639]:     await self.flush_status()
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/local/bin/jetforce", line 590, in flush_status
May 18 15:49:04 hermes jetforce[31639]:     await self.writer.drain()
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/lib/python3.7/asyncio/streams.py", line 348, in drain
May 18 15:49:04 hermes jetforce[31639]:     await self._protocol._drain_helper()
May 18 15:49:04 hermes jetforce[31639]:   File "/usr/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
May 18 15:49:04 hermes jetforce[31639]:     raise ConnectionResetError('Connection lost')
May 18 15:49:04 hermes jetforce[31639]: ConnectionResetError: Connection lost
```
Bomadillo also complains about an expired cert, and that the cert hostname does not match.

**Comment by michael-lazar** [comment]
It looks like bombadillo is not sending the correct ``<CR><LF>`` line ending at the end of the request.

Even though some of the other server implementations are more lenient and make the ``<CR>`` part optional, the current gemini spec is clear about this being a hard requirement.

> Gemini requests are a single CRLF-terminated line with the following
> structure:
> 
> <URL><CR><LF>
> 
> <URL> is a UTF-8 encoded absolute URL, of maximum length 1024 bytes.
> If the scheme of the URL is not specified, a scheme of gemini:// is
> implied.


> Bomadillo also complains about an expired cert, and that the cert hostname does not match.

Both of these things are encoded into your x509 certificate itself, and aren't controlled by jetforce. You can quickly inspect the certificate if you load your gemini site in https://portal.mozz.us and click the "[view cert]" link at the top.

**Comment by kayew** [comment]
So the problem is just bombadillo itself, and not a problem with my cert...?

**Comment by makeworld-the-better-one** [comment]
> It looks like bombadillo is not sending the correct `<CR><LF>` line ending at the end of the request.

As far as I can tell from the Bombadillo source, this is not true. See [this line](https://tildegit.org/sloum/bombadillo/src/branch/master/gemini/gemini.go#L202). @kayew Make sure you're using the latest version though I guess.

**Comment by kayew** [comment]
I fail to understand why this is happening, even though I'm on the latest version. I guess this'll need to be reported to the devs.

**Comment by michael-lazar** [comment]
> As far as I can tell from the Bombadillo source, this is not true. See this line.

Fair enough, thanks for the info.
