### ISSUE TITLE
separate diagnostic script into own project

### ISSUE THREAD

**Issue by mk270** [michael-lazar/jetforce#22]
Please consider spinning out the test script into its own independent git project; it's pretty important for Gemini to have some kind of server conformance testing suite, and such a thing may attract a different  developer group.

**Comment by michael-lazar** [comment]
I think you're right and this is probably a good idea. There are no shared dependencies and it really only ended up here out of convenience. Any ideas for what I should call it?

**Comment by mk270** [comment]
Not my strong suit. Maybe `gemini_conformance.py` or something like that. Though I'm not squeamish about using the term "torture", in the tradition of `smbtorture` and so on, I see no need to follow it either.

**Comment by michael-lazar** [comment]
New repo is here: https://github.com/michael-lazar/gemini-diagnostics

I'll remove the ``jetforce-diagnostics`` script from this repo in the next version release.

**Comment by mk270** [comment]
Thanks

**Comment by mk270** [comment]
(incidentally, this tool should be announced on the gemini mailing list - it's super useful)

**Comment by michael-lazar** [comment]
It was!

https://lists.orbitalfox.eu/archives/gemini/2020/000296.html

**Comment by mk270** [comment]
Ah good - might be worth a reminder (though someone else has just mentioned it on the list!)
