### ISSUE TITLE
Jetforce allows for arbitrary directory traversal, causing big security issues

### ISSUE THREAD

**Issue by jamestomasino** [michael-lazar/jetforce#24]
Jetforce makes it easy to do arbitrary filesystem traversal by using relative links outside of the root of the gemini home. 
For instance, you can browse "gemini://tilde.black/../../etc/motd"

Running the server as a restricted access daemon user helps, but it still has issues. Since the user running jetforce needs to be able to read the public & private keys for the server, and because those people browsing your gemini server are doing so AS that user, if the path is known your gemini server's private key can be read in plain text directly over gemini.

We need a way to hard-limit directory traversal so it cannot go 'up' from the root directory.

**Comment by makeworld-the-better-one** [comment]
I emailed you about this, btw.

**Comment by michael-lazar** [comment]
Thank you both for reporting the issue, I was gone all day and I'm just sitting down to look at this now.

There was an attempt to guard against escaping from the root directory, but there was a bug in the code that I believe I have identified and fixed. The summary is that I was looking at the last component of the normalized path for a ``..``, when I should have been looking at the first component. 🤦 

https://github.com/michael-lazar/jetforce/commit/50bde8b7f2edf89b56805ad9fb30ac3833eb6d65

I branched directly off of the last release (v0.2.2) and published a new bugfix release (v0.2.3) with only this change in it. This version has been uploaded to pip.

https://github.com/michael-lazar/jetforce/releases/tag/v0.2.3

https://pypi.org/project/Jetforce/0.2.3/

**Comment by makeworld-the-better-one** [comment]
I just updated and now any relative links do not work, if they are not in the root directory. For example, a file at `/var/gemini/somefolder/file.gmi`, that links to `/var/gemini/somefolder/other.gmi`, using a relative link, now returns code 51.

**Comment by michael-lazar** [comment]
Do you mind posting your server log for the 51 error? I don't see any obvious relation between this and the change that I made.

**Comment by makeworld-the-better-one** [comment]
You know, what I think it was my Bombadillo update. I'll check it out tomorrow and let you know.

**Comment by LickTheCheese** [comment]
isn't the client supposed to take care of relative linking, not the server?

**Comment by makeworld-the-better-one** [comment]
Yes, this is caused by my client, sorry for the confusion. The issue can now be closed.

**Comment by jamestomasino** [comment]
I can confirm that updating to the latest version and restarting the service fixes the issue on tilde.black. Thanks!

**Comment by michael-lazar** [comment]
I posted an announcement on the gemini mailing list, hopefully that will reach anyone who might be running a jetforce server in production. Thank you again for reporting this issue, I hate security bugs 🙏
