### ISSUE TITLE
Response address

### ISSUE THREAD

**Issue by kseistrup** [michael-lazar/jetforce#26]
I have jetforce v0.2.3 listening on `[::]` only, and serving contents for a hostname that resolves to two different IPv6 addresses: a traditional public IPv6 address and an yggdrasil address in the CIDR block `0200::/7`.

More often than not, when a client is connecting over the yggdrasil address, jetforce will seemingly (if the logfile is any indication) respond over traditional IPv6, and I have also seen it the other way around.

It this just an artifact because jetforce looks up the IP address of its hostname and uses whatever comes first to write its log message, or does it really respond over a different address than the request (that can't happen with TLS, can it?)?

Cheers.

**Comment by makeworld-the-better-one** [comment]
Hey, I recognize that profile pic from Scuttlebutt! Running a Gemini server on Yggdrasil sounds awesome, afaik you're the first. Sorry I can't be of help for this issue, but could you share the IP?

**Comment by kseistrup** [comment]
Haha, cool! What's your Scuttlebutt ID?

The hostname is port1965.eu.

**Comment by makeworld-the-better-one** [comment]
I haven't used it in a long time unfortunately, I don't remember. But thanks for sharing, and that's a great domain!

**Comment by michael-lazar** [comment]
Hi!

I have no experience with yggdrasil (it sounds neat though) and only limited experience with IPv6, so apologies if I'm missing something fundamental here...

Jetforce logs the remote client IP address, not the server IP address that the connection is made to. So I'm not sure I understand unless you are saying that connections can only be made from

- client yggdrasil IPv6 -> server yggdrasil IPv6

and not from

- client IPv6 -> server yggdrasil IPv6

or the other way around.

The client's IP address is coming straight from the kernel socket and jetforce doesn't do anything in particular to try to resolve it. Python uses ``getpeername`` which is a thin wrapper around the linux syscalls.

- https://www.man7.org/linux/man-pages/man2/getpeername.2.html
- https://www.man7.org/linux/man-pages/man3/inet_ntop.3.html

For IPv6, this returns a tuple of ``(host, port, flowinfo, scopeid)``. I take the ``host`` part and discard the rest.

**Comment by kseistrup** [comment]
Perhaps a snippet from my syslog is the best way to tell what I see. Lets say we have

```sh
IPv6='2a00:…:55d7'
YGG='031f:…:55d7'
```

Then I see the following lines in syslog:

```sh
$IPV6 [27/May/2020:22:52:15 +0200] "gemini://port1965.eu" 31 "gemini://port1965.eu/" 26
$YGG  [27/May/2020:22:52:15 +0200] "gemini://port1965.eu/" 20 "text/gemini" 343
```

I have taken the first line to be the request and the second one to be the response, but perhaps that's incorrect?

**Comment by makeworld-the-better-one** [comment]
That is correct, as far as my logs go.

**Comment by michael-lazar** [comment]
The log format is one line per-request:

```
{remote_addr} [{timestamp}] {url} {status} {meta} {response_size}
```

So in your log snippet:

- The client made a request to the server for "gemini://port1965.eu", the server responded with a "31 REDIRECT - PERMANENT" and the meta of the response contained the redirect URL (which added the slash to the end of the URL)
- The client made a second request to the server for "gemini://port1965.eu/". The server responded with "20 SUCCESS", the meta was "text/gemini", and the response body was 343 bytes.

It appears that your client is resolving the domain differently between the first and the second request.

**Comment by kseistrup** [comment]
Ah, so both of the lines are responses from the server to the client. Now I understand.

I am using the AV-98 navigator, and it seems it doesn't cache DNS requests, and I have told my resolver to shuffle responses if there is more than one answer to a request.

Now it all makes sense. Thanks!
