### ISSUE TITLE
URLs with spaces

### ISSUE THREAD

**Issue by jamestomasino** [michael-lazar/jetforce#29]
It seems like Jetforce isn't respecting URLs with encoded spaces (%20). I'm working on setting up Cosmic Voyage on gemini and many of the ship names (and directories) have spaces. I've encoded those as %20s and tried encoding them as + as well, but neither works.

Interestingly, if I use the auto-generated directory indexing and the files contain spaces a similar problem occurs. In this case the space is literally there, throwing off the labeling and links both.

I think the server just needs to do a little encode/decode work with %20 and it should be good.

**Comment by michael-lazar** [comment]
Thanks, it somehow slipped my mind that the path component also needs to be URL encoded.

I added a commit to fix this here 9cc4a32, will likely do another bugfix release either tonight or tomorrow.

**Comment by michael-lazar** [comment]
v0.3.2 has now been released with this fix
