### ISSUE TITLE
The status is written using a tab which is out of spec

### ISSUE THREAD

**Issue by makeworld-the-better-one** [michael-lazar/jetforce#31]
This can be seen in [this line](https://github.com/michael-lazar/jetforce/blob/master/jetforce/protocol.py#L198).

Under section 3.1 of the [Gemini spec](https://gemini.circumlunar.space/docs/specification.html), you can see that status codes and meta string should be separated by a space and not a tab.

**Comment by michael-lazar** [comment]
Thanks, fixed here 702c3dd and will be included in the next release.
