### ISSUE TITLE
Reverse-proxying

### ISSUE THREAD

**Issue by makew0rld** [michael-lazar/jetforce#36]
Is there an easy way to set up a reverse proxy in Jetforce, maybe using a `CompositeApplication`? So all requests for `example.com` use the static file server or some Jetforce app, and all the requests for `app.example.com` are proxyed to `localhost:12345` or whatever.

Would client certs be carried over too?

**Comment by michael-lazar** [comment]
This is a capability that I always wanted for gopher, and I would love to add support for it in jetforce if possible. I think the ``CompositeApplication`` would likely be the way to go, along with using a producer (#33) for efficient streaming. There are some open questions that I don't have good answers for right now.

Client certificates are a problem. If jetforce decrypts the TLS connection then AFAIK there's no way that it could re-encrypt it to send to the target server with the same client certificate.

What might be interesting is if a reverse proxy could avoid decrypting the connection at all, and instead act like a dumb TCP tunnel that forwards all traffic to a another port. If the SNI is not [encrypted](https://blog.cloudflare.com/encrypted-sni/) then the proxy could probably sniff the hostname from the client hello message. I don't think something like this would be possible in jetforce without making some serious changes to the server code though. That would probably be better off as a separate tool written in something like rust or go.

**Comment by makeworld-the-better-one** [comment]
Happy to hear it! And yeah, client certs wouldn't work, I see that now. I like your idea at the end though, that would be a cool tool. I don't like that it has to rely on insecure SNI, but it would work for the time being.

**Comment by makeworld-the-better-one** [comment]
Here, I found some SNI proxies. I haven't tested them, but they should work for Gemini out of the box.

https://github.com/dlundquist/sniproxy

https://github.com/fangdingjun/sniproxy

**Comment by pitr** [comment]
FYI you can use [nginx ssl preread module](http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html) instead, which I discovered when I needed a similar functionality. I believe Apache has something similar.

**Comment by makeworld-the-better-one** [comment]
Even though HTTP isn't being used? Interesting...

**Comment by pitr** [comment]
Not quite. My understanding is that it works on tcp level, and only peeks into the tls layer to look at the ClientHello message.
