### ISSUE TITLE
Wrong MIME type ‘text/plain’ assigned to some ebooks

### ISSUE THREAD

**Issue by kseistrup** [michael-lazar/jetforce#38]
I have a few ebooks for download in EPUB, MOBI and PDF formats over the Gemini protocol.

**Jetforce v0.5.0** logs:

```txt
 […] "gemini://example.net/ebook.epub" 20 text/plain 1738936
 […] "gemini://example.net/ebook.mobi" 20 text/plain 1597628
 […] "gemini://example.net/ebook.pdf" 20 application/pdf 2930121
```

However,

```py
>>> import mimetypes
>>> mimetypes.guess_type("gemini://example.net/ebook.epub")
('application/epub+zip', None)
>>> mimetypes.guess_type("gemini://example.net/ebook.mobi")
('application/x-mobipocket-ebook', None)
>>> mimetypes.guess_type("gemini://example.net/ebook.pdf")
('application/pdf', None)
```

Does jetforce give up too early and wrongfully assigns the MIME type ‘text/plain’ to some formats?

**Comment by michael-lazar** [comment]
Jetforce is using the same mimetypes library, but it will default the ``text/plain`` if it can't find a corresponding entry:

https://github.com/michael-lazar/jetforce/blob/7215195b8c0a7eb6001f25c9ba439703e8e676f4/jetforce/app/static.py#L193-L201

I know that python tries to load the mimetype definitions from files on the OS, but it will also fallback to a set of definitions that are shipped with python. Maybe the user that you're running the jetforce server as doesn't have access to read those files?

```python
>>> import mimetypes
>>> for file in mimetypes.knownfiles:
...     print(file)
...
/etc/mime.types
/etc/httpd/mime.types
/etc/httpd/conf/mime.types
/etc/apache/mime.types
/etc/apache2/mime.types
/usr/local/etc/httpd/conf/mime.types
/usr/local/lib/netscape/mime.types
/usr/local/etc/httpd/conf/mime.types
/usr/local/etc/mime.types
```

**Comment by kseistrup** [comment]
> Maybe the user that you're running the jetforce server as doesn't have access to read those files?

It does have read access to those files.

If I let systemd launch a shell-script that first run a short python script like the one above (and also what kind of MIME types it thinks the EPUB and MOBI URLs are) and then execs into jetforce, this is what I see in syslog:

```
Jul 16 22:39:22 umbra gemini[1045309]: /etc/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /etc/httpd/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /etc/httpd/conf/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /etc/apache/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /etc/apache2/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /usr/local/etc/httpd/conf/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /usr/local/lib/netscape/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /usr/local/etc/httpd/conf/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: /usr/local/etc/mime.types
Jul 16 22:39:22 umbra gemini[1045309]: ('application/epub+zip', None)
Jul 16 22:39:22 umbra gemini[1045309]: ('application/x-mobipocket-ebook', None)
Jul 16 22:39:22 umbra gemini[1045286]: You are now riding on...
Jul 16 22:39:22 umbra gemini[1045286]: _________    _____________
Jul 16 22:39:22 umbra gemini[1045286]: ______  /______  /___  __/_______________________
Jul 16 22:39:22 umbra gemini[1045286]: ___ _  /_  _ \  __/_  /_ _  __ \_  ___/  ___/  _ \
Jul 16 22:39:22 umbra gemini[1045286]: / /_/ / /  __/ /_ _  __/ / /_/ /  /   / /__ /  __/
Jul 16 22:39:22 umbra gemini[1045286]: \____/  \___/\__/ /_/    \____//_/    \___/ \___/
Jul 16 22:39:22 umbra gemini[1045286]: An Experimental Gemini Server, v0.5.0
Jul 16 22:39:22 umbra gemini[1045286]: https://github.com/michael-lazar/jetforce
Jul 16 22:39:22 umbra gemini[1045286]: Server hostname is example.net
Jul 16 22:39:22 umbra gemini[1045286]: TLS Certificate File: /etc/gemini/certs/example.net.crt
Jul 16 22:39:22 umbra gemini[1045286]: TLS Private Key File: /etc/gemini/certs/example.net.key
Jul 16 22:39:22 umbra gemini[1045286]: Listening on [::]:1965
```

and the EPUB and MOBI lines are present in the very first `mime.types` file:

```sh
$ awk '$2 == "epub"' /etc/mime.types
application/epub+zip				epub
$ awk '$2 == "mobi"' /etc/mime.types
application/x-mobipocket-ebook			mobi
```

**Comment by kseistrup** [comment]
PS: A client (in this case AV-98) trying to download the file will fail with “Could not decode response body using UTF-8 encoding declared in header!”

**Comment by kseistrup** [comment]
Ah, found the bug:

We have

```py
    44          self.mimetypes = mimetypes.MimeTypes()
```

and

```py
   197          mime, encoding = self.mimetypes.guess_type(filename)
```

But if we:

```py
>>> import mimetypes
>>> mt = mimetypes.MimeTypes()
>>> mt.guess_type("gemini://example.net/ebook.mobi")
(None, None)
```

Boom! :bomb:

**Comment by makeworld-the-better-one** [comment]
> it will default the `text/plain` if it can't find a corresponding entry

I would argue this is a bad behaviour, and that something like `application/octet-stream` or similar should be used instead, to prevent clients from trying to display binary data.

**Comment by michael-lazar** [comment]
> > it will default the `text/plain` if it can't find a corresponding entry
> 
> I would argue this is a bad behaviour, and that something like `application/octet-stream` or similar should be used instead, to prevent clients from trying to display binary data.

Agreed

**Comment by michael-lazar** [comment]
https://bugs.python.org/issue38656

**Comment by kseistrup** [comment]
The fix works for me. Thanks! :pray:
