### ISSUE TITLE
[Feature Request] Default Request Handler

### ISSUE THREAD

**Issue by ggramaize** [michael-lazar/jetforce#45]
Hi,

One feature it would be nice to have is a default request handler, which, once set up, would be called in last resort before returning a "file not found" error.

The idea behind this is to enable a CGI module to handle "fancy" URL routing inside CGI applications (e.g. `gemini://example.com/blog/a-new-post/` instead of `gemini://example.com/cgi-bin/blog.cgi?a-new-post` ) without having to add URL rewriting on your side. 

Kind regards

**Comment by maimere** [comment]
Hello

I had the very same insight, so this is what I did:

Instead of naming the file `blog.cgi` and dealing with `?a-new-post` through `$QUERY_STRING`, try this: call the file simply `blog`, and when you open `gemini://domain.com/blog/a-new-post`, `$PATH_INFO` will return you `/a-new-post`, which can easily be used to call your `/a-new-post.gmi` file, for example.

**Comment by michael-lazar** [comment]
That's slick!

**Comment by ggramaize** [comment]
> Hello
> 
> I had the very same insight, so this is what I did:
> 
> Instead of naming the file `blog.cgi` and dealing with `?a-new-post` through `$QUERY_STRING`, try this: call the file simply `blog`, and when you open `gemini://domain.com/blog/a-new-post`, `$PATH_INFO` will return you `/a-new-post`, which can easily be used to call your `/a-new-post.gmi` file, for example.

Thanks for that feedback, which I find very interesting.

However, in the scope of this ticket, my intent is to get a similar mechanism as what's provided by the `FallbackResource` directive in [Apache 2.4's mod_dir](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#fallbackresource). The purpose of this is to be able to serve the whole application through a micro-framework (with which my first tests are successful).

I can also deal with this by doing URL rewriting, but that solution seems to be more complex to implement.

**Comment by michael-lazar** [comment]
I see what you mean. Something like that could be accomplished by subclassing the static directory application like this:

```python
#!/usr/local/env python3
from jetforce import GeminiServer, StaticDirectoryApplication, Status


class FallbackCGIApplication(StaticDirectoryApplication):

    def serve_static_file(self, request):
        response = super().serve_static_file(request)
        if response.status == Status.NOT_FOUND:
            return self.run_cgi_script("/path/to/fallback.cgi", request.environ)
        else:
            return response


app = FallbackCGIApplication("/var/gemini")

if __name__ == "__main__":
    # Add the host, port, etc... arguments here that are normally set through the command line
    server = GeminiServer(app, host="...", hostname="...")
    server.run()
```

I'm trying to avoid jetforce going down the path of Apache will a billion configuration options and module extensions. Not that there's anything wrong with that type of server (Molly-Brown would be the closest gemini equivalent AFAIK), but it doesn't sound like fun for me to maintain. I'm trying to push people towards configuration through code like above, and treating jetforce more like a framework to build on top of. I should probably put a disclaimer to that effect in the readme.

**Comment by ggramaize** [comment]
Well, the way you're suggesting to handle that issue replies to my needs quite elegantly.

I understand the point you're trying to make by keeping jetforce simple, but extendable.

Thanks for your advice.
