### ISSUE TITLE
py.typed file

### ISSUE THREAD

**Issue by sose-iwnl** [michael-lazar/jetforce#47]
It appears the project is missing a py.typed file to indicate that the project supports type checking.

**Comment by michael-lazar** [comment]
Hi, do you have any more information on how this is supposed to work? I read through [PEP 561](https://www.python.org/dev/peps/pep-0561/) but I'm still confused. This looks like something that's required if you have stub files, but I only use the inline type hints and I don't need to support python 2. It's unclear to me what I need a ``py.typed`` file for.

**Comment by sose-iwnl** [comment]
From what I understand reading [the mypy docs](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages), the py.typed file is required whether using stubs or inline type hints. 

I can say for certain that when importing jetforce as a module and attempting to run mypy on the code, I get an error. When adding the 'py.typed' file to the module, mypy behaves correctly.

**Comment by michael-lazar** [comment]
Thanks! The Mypy docs are definitely better. I'll make sure this is added for the next release.
