### ISSUE TITLE
FYI: Now available from AUR

### ISSUE THREAD

**Issue by kseistrup** [michael-lazar/jetforce#66]
Jetforce is now available from AUR:

* https://aur.archlinux.org/packages/python-jetforce

ArchLinux users can install it with e.g.:

```sh
  yay -S python-jetforce
```

**Comment by michael-lazar** [comment]
Thanks!

**Comment by kseistrup** [comment]
From v1.0.0 the package name on AUR is `jetforce`:

* https://aur.archlinux.org/packages/jetforce
