### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by rnwgnr** [michael-lazar/jetforce#73]
I'm not completely sure that jetforce is the culprit, but atleast that is my guess at the moment.

Debian 12 Bookworm will ship with Python 3.11. I've setup a testmachine and tried to install my project that requires `jetforce`.

It seems that jetforce 0.9.1 has (directly or due to some sub-dependency) a dep on `twisted` version 20.3.0.
This twisted version is not compatbile with python 3.11 and fails to compile.

If i try to force `twisted` to version 22.1.0 via my `pyproject.toml` `jetforce` will fall back to version 0.8.2.

**Comment by michael-lazar** [comment]
Try installing jetforce from the master branch of this repo. I recently bumped the dependency requirements for twisted and I suspect it will fix your issue.

https://github.com/michael-lazar/jetforce/blob/master/setup.py#L20

**Comment by rnwgnr** [comment]
Thanks for the quick response and the hint.
Installation was successfull when pulling from master - will do some testing now.

**Comment by michael-lazar** [comment]
Fixed in [v0.10.0](https://github.com/michael-lazar/jetforce/releases/tag/v0.10.0)!
