### ISSUE TITLE
This server does not allow proxy requests

### ISSUE THREAD

**Issue by ygagnon** [michael-lazar/jetforce#74]
I was very hopeful about getting this Gemini Server up and running on a small SBC on my home network, .. but although I've succeeded at getting the server up and running, it appears to be refusing all connections with the following error:

**This server does not allow proxy requests**

Here are the commands that I'm running to get the server up and running (I've tried both with no success):

**jetforce --host "0.0.0.0" --dir /var/www/gemini**

**jetforce --host "0.0.0.0" --dir /var/www/gemini --tls-certfile "/tmp/localhost.crt" --tls-keyfile "/tmp/localhost.key"**

It's my understanding that temporary cert and key files get auto generated if none are specified, .. though it was unclear if I needed to specifically point to those auto generated files when running the server .. which is why I tried both methods.

And yes, .. I did physically create the "/var/www/gemini" folder that I'm specifying, .. and I do have a properly formatted "index.gmi" file contained within that folder.

I've also tried specifying different hostnames (such as the server's dedicated IP address, as well as it's network hostname)  .. still with no luck.  And I've tried accessing it locally using amfora, as well as remotely from a Windows 11 PC using Geminaut.  Wwith the latter .. I get the following messages: 

**"Note: the certificate from: 192.168.1.99 is expired or invalid"**

**Permanent failure (status 5X)
This server does not allow proxy requests**

So what is it that I'm doing wrong, or that I'm missing here?

Thanks,
-- Yvan

**Comment by michael-lazar** [comment]
You need to tell jetforce what your server's hostname is, e.g.

```
jetforce --hostname mysite.example.com
```

or

```
jetforce --hostname "192.168.1.99"
```

Otherwise it will only accept connections for "localhost" by default. This also probably explains the error from Amfora, the generated TLS certificate also uses the `--hostname` value to populate the certificate's common name field.

**Comment by ygagnon** [comment]
As I'd mentioned, I'd already tried specifying both the server's dedicated IP as well as the hostname .. and the connection still gets refused.

Here's the error that amfora is giving me when I specify the ip address as the hostname (and omit the paths to the certificates):

 Failed to connect to the server:     ║                                                                            ║  hostname does not verify: x509: cannot  ║                                                                            ║  validate certificate for 192.168.1.99   ║                                                                            ║ because it doesn't contain any IP SANs.

**Comment by michael-lazar** [comment]
> As I'd mentioned, I'd already tried specifying both the server's dedicated IP as well as the hostname .. and the connection still gets refused.

It sounds like you have tried a bunch of different things at this point, and some different errors / problems are getting mixed together and confusing the issue.

> Here are the commands that I'm running to get the server up and running (I've tried both with no success):
>
> jetforce --host "0.0.0.0" --dir /var/www/gemini
>
> jetforce --host "0.0.0.0" --dir /var/www/gemini --tls-certfile "/tmp/localhost.crt" --tls-keyfile "/tmp/localhost.key"

Neither of these contain the ``--hostname`` argument. If you are running jetforce with the ``--hostname`` flag, show me the exact command that you are running. If not, you need to set the ``--hostname`` flag as described in the README.

https://github.com/michael-lazar/jetforce#setting-the-hostname

**Comment by ygagnon** [comment]
My apologies .. you are correct that I've been mixing up the "--host" and "--hostname" flags.  I've succeeded at getting the server to accept requests be running the following command:

jetforce --host "0.0.0.0" --hostname "khadas.local" --dir /var/www/gemini

Thanks so much for your help .. and for your patience.

-- Yvan
